---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-dns-service-for-shoot-services
rules:
  - apiGroups:
      - dns.gardener.cloud
    resources:
      - dnsentries
      - dnsentries/status
    verbs:
      - get
      - list
      - update
      - watch
      - create
      - delete
