apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
