apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}